image: code.ornl.gov:4567/bt2/parallellinearalgebra
test:
  stage: test
  script:
    - export MAGMA_ROOT=/opt/magma
    - mkdir build
    - cd build
    - cmake -DBUILD_FOR_GPU=ON ..
    - make
    - cd src
    - ./main 10
