test:
  stage: test
  script:
    - mkdir build
    - cd build
    - cmake -DBUILD_FOR_GPU=ON -DPLA_WITH_CLANG_FORMAT=ON -DCMAKE_PREFIX_PATH=/opt/magma ..
    - make
    - ctest  -V
    - make format
    - git diff --exit-code
